CLASS zseagull_cl_matdoc_event_consm DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC
  FOR EVENTS OF I_materialdocumenttp.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZSEAGULL_CL_MATDOC_EVENT_CONSM IMPLEMENTATION.
ENDCLASS.
